### ISSUE TITLE
Italic conflicts with verse blocks

### ISSUE THREAD

**Issue by habamax** [habamax/vim-asciidoctor#43]
# plugin params

```
let g:asciidoctor_syntax_conceal = 1
```

# Test doc

```
= Test

.Regular verse
[verse]
_______
this
should
be
on
different
lines
_______
```

# Result
![image](https://user-images.githubusercontent.com/234774/71510629-8a656280-28a0-11ea-9e0f-94c1b56a1d56.png)

![vim-asciidoctor-italic](https://user-images.githubusercontent.com/234774/71510685-bc76c480-28a0-11ea-963e-a68bd6cc09c3.gif)

**Comment by habamax** [comment]
Hi @mg979, fyi

Buon Natale!

**Comment by mg979** [comment]
@habamax hey thanks anche a te!

I think it happens because quote blocks aren't defined, if I add after https://github.com/habamax/vim-asciidoctor/blob/f062ee3ef09b3b5abb3bd815007fb6c23330e47d/syntax/asciidoctor.vim#L189

this:

```vim
syn region asciidoctorQuoteBlock   matchgroup=asciidoctorBlock start="^\z(____\+\)\s*$" end="^\z1\s*$" contains=@asciidoctorInnerBlock,@asciidoctorInline,@Spell,asciidoctorComment
```

it is highlighted correctly, let me know. There may be more kinds of blocks that still need to be defined.

**Comment by habamax** [comment]
Thx @mg979
