### ISSUE TITLE
Default highlighting for Indented, Listing, Literal blocks

### ISSUE THREAD

**Issue by habamax** [habamax/vim-asciidoctor#54]
Currently default highlighting is linked to Comment, which might be quite "strong".

Personally I would prefer to link them to Normal -- let it be just a normal text, unless user or colorscheme redefines it to whatever they like.

Hi @mg979, any thoughts on it?

**Comment by habamax** [comment]
With current settings and default theme:
![image](https://user-images.githubusercontent.com/234774/73732648-9a981980-474b-11ea-9ec6-463616d0148a.png)

**Comment by habamax** [comment]
zellner:
![image](https://user-images.githubusercontent.com/234774/73732900-0ed2bd00-474c-11ea-957e-cf5b7e6c14af.png)

**Comment by habamax** [comment]
For my theme I have defined it like this:

![image](https://user-images.githubusercontent.com/234774/73733213-9a4c4e00-474c-11ea-8293-536173f57a97.png)

**Comment by habamax** [comment]
And there are also themes with italic comments -- and it looks even worse then strong colors.

**Comment by mg979** [comment]
> Personally I would prefer to link them to Normal

I generally use color schemes with subtle comments, so `Comment` works best for me, but I don't care what is default as long as I can set my own. Just don't link it to Normal, because it causes [issues](https://github.com/neovim/neovim/issues/9019). Rather, don't define an highlight for it so it will have no default highlight and wil fallback to Normal.

**Comment by mg979** [comment]
Also, to have a default highlight is better in my opinion, so that even if a colorscheme reassigns it, at least it's obvious that it has a highlight of its own, or one could think it's not possible to highlight it differently. So I'd choose a color different from Normal anyway, which one isn't important for me.

**Comment by mg979** [comment]
One last thing: I also noticed that highlight for indented blocks can slow down a lot the scrolling, I put this in my ftplugin:

    syn sync maxlines=100

You could mention it in the documentation, if one thinks scrolling becomes slow.

**Comment by habamax** [comment]
> 
> 
> One last thing: I also noticed that highlight for indented blocks can slow down a lot the scrolling, I put this in my ftplugin:
> 
> ```
> syn sync maxlines=100
> ```
> 
> You could mention it in the documentation, if one thinks scrolling becomes slow.

Currently in syntax file we have the opposite:

    syn sync minlines=100

:)

It was one of my tries to fix sync issue with block elements.

I will make it `maxlines` and test for awhile.

**Comment by habamax** [comment]
> Actually, to have a default highlight is better in my opinion, so that even if a colorscheme reassigns it, at least it's obvious that it has a highlight of its own, or one could think it's not possible to highlight it differently. So I'd choose a color different from Normal anyway, which one isn't important for me.

Okay, let it be the way it is now. :)

Thanks!
